### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/MultiWOZ_2.0/db/attraction_db_processed.json'

### ISSUE THREAD

**Issue by zhifei-0321** [whatissimondoing/MDTOD#1]
This file is missing, will it be uploaded in the future, or do I have to download it from somewhere?

**Comment by zhifei-0321** [comment]
i could not find the pre-processed MultiWOZ2.0 and MultiWOZ2.1,Has it been uploaded，I'd appreciate it if you'd get back to me.

**Comment by whatissimondoing** [comment]
> This file is missing, will it be uploaded in the future, or do I have to download it from somewhere?

You need to uncomment lines 52-54 of preprocess.py to generate these data.

**Comment by whatissimondoing** [comment]
> i could not find the pre-processed MultiWOZ2.0 and MultiWOZ2.1,Has it been uploaded，I'd appreciate it if you'd get back to me.

We did not upload the preprocessed data, but you can run preprocess.py according to the README to preprocess it yourself.

**Comment by zhifei-0321** [comment]
thank u so much
